#!/bin/bash
#
#SBATCH --job-name=BIDS_Conversion
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 1:00:00
## %A == SLURM_ARRAY_JOB_ID
## %a == SLURM_ARRAY_TASK_ID

if [ ${SLURM_ARRAY_TASK_ID} -lt 10 ]; then
    in="00${SLURM_ARRAY_TASK_ID}"
elif [  ${SLURM_ARRAY_TASK_ID} -lt 100 ]; then
    id="sub-0${SLURM_ARRAY_TASK_ID}"
else 
    id="sub-${SLURM_ARRAY_TASK_ID}" 
fi

input=$1
cmd=${input//SUBJECT/$id}
echo $cmd